services:
  database:
    &database
    profiles:
      - prod
    build:
      dockerfile: ./config/mysql/Dockerfile
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - "db_data:/var/lib/mysql/"
  
  database-dev:
    <<: *database
    profiles:
      - dev
    ports:
      - 3306:3306
  
  php:
    &php
    profiles:
      - prod
    restart: on-failure
    build:
      dockerfile: ./config/php/Dockerfile.prod
    volumes:
      - session_data:/var/www/sessions/
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
  
  php-dev:
    <<: *php
    profiles:
      - dev
    build:
      dockerfile: ./config/php/Dockerfile.dev
    volumes:
      - ./php/:/var/www/html/
      - ./vendor/:/var/www/html/vendor/
      - session_data:/var/www/sessions/
    ports:
      - 9000:9000
    depends_on:
      - database-dev
  
  rust:
    &rust
    profiles:
      - prod
    restart: on-failure
    build:
      dockerfile: ./config/rust/Dockerfile.prod
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@database:3306/${DB_DATABASE}
      - OVERSEER_ROOT=/php/
    volumes:
      - session_data:${OVERSEER_PHP_SESSIONS_ROOT}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
  
  rust-dev:
    <<: *rust
    profiles:
      - dev
    build:
      dockerfile: ./config/rust/Dockerfile.dev
    volumes:
      - ./rust/:/rust/
      - ./php/:/php/
      - session_data:${OVERSEER_PHP_SESSIONS_ROOT}
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@database-dev:3306/${DB_DATABASE}
      - OVERSEER_ROOT=/php/
    ports:
      - 8010:8010
    depends_on:
      - database-dev

volumes:
  db_data:
  session_data:
